# Generated by Django 4.0.1 on 2023-03-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
