# Generated by Django 4.2 on 2023-08-17 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_alter_wishlistitem_options'),
        ('base', '0008_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='wishlist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wishlists.wishlistitem'),
        ),
    ]
