# Generated by Django 4.2 on 2023-08-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_alter_wishlistitem_options'),
        ('base', '0009_event_wishlist_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='wishlist_item',
        ),
        migrations.AddField(
            model_name='event',
            name='wishlist_item',
            field=models.ManyToManyField(to='wishlists.wishlistitem'),
        ),
    ]
