# Generated by Django 4.2 on 2023-09-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_alter_wishlistitem_options'),
        ('base', '0010_remove_event_wishlist_item_event_wishlist_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='wishlist_item',
            field=models.ManyToManyField(blank=True, null=True, to='wishlists.wishlistitem'),
        ),
    ]
