# Generated by Django 4.2 on 2023-09-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_event_wishlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='added_by_host',
            field=models.BooleanField(default=False),
        ),
    ]
