# Generated by Django 4.0.1 on 2023-10-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_alter_wishlistitem_options'),
        ('base', '0012_payment_added_by_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='wishlist_item',
            field=models.ManyToManyField(blank=True, to='wishlists.WishlistItem'),
        ),
    ]
