apiVersion: apps/v1
kind: Deployment
metadata:
  name: birthday-organizer-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: birthday-organizer-celery
  template:
    metadata:
      labels:
        app: birthday-organizer-celery
    spec:
      containers:
      - name: celery
        image: "europe-central2-docker.pkg.dev/birthday-organizer-380215/containers/birthday-organizer-django-image:latest"
        ports:
        - containerPort: 80
        command: ["bash", "/var/birthday_organizer/start", "include-celery"]
        env:
        - name: BIRTHDAY_ORGANIZER_ENV
          value: "prd"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgre-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgre-credentials
              key: password
        - name: DJANGO_KEY
          valueFrom:
            secretKeyRef:
              name: django-key
              key: djangokey
        - name: GMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: gmail-credentials
              key: gmailpass
        - name: GMAIL_USER
          valueFrom:
            secretKeyRef:
              name: gmail-credentials
              key: gmailuser
