# Generated by Django 4.0.1 on 2022-06-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_payment_amount_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=10000),
        ),
    ]
