# Generated by Django 4.0.1 on 2022-12-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='celebrant',
        ),
        migrations.RemoveField(
            model_name='event',
            name='host',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
