# Generated by Django 4.0.1 on 2022-06-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='when',
        ),
    ]
