# Generated by Django 4.0.1 on 2022-06-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_comment_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='when',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
