# Generated by Django 4.0.1 on 2022-06-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_comment_when'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='when',
            new_name='created',
        ),
    ]
