# Generated by Django 4.0.1 on 2022-06-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_rename_when_comment_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
    ]
