# Generated by Django 4.2 on 2023-08-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ('-active', 'title')},
        ),
    ]
