apiVersion: apps/v1
kind: Deployment
metadata:
  name: birthday-organizer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: birthday-organizer-db
  template:
    metadata:
      labels:
        app: birthday-organizer-db
    spec:
      containers:
      - name: postgre
        image: "europe-west1-docker.pkg.dev/primeval-proton-378710/birthday-organier-containers/birthday-organizer-postgre-image:latest"
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresdata
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgre-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgre-credentials
              key: password
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgresql-data-claim
    