apiVersion: "v1"
kind: "Service"
metadata:
  name: "birthday-organizer-db-service"
  namespace: "default"
spec:
  ports:
  - protocol: "TCP"
    port: 5432
    targetPort: 5432
  selector:
    app: "birthday-organizer-db"
  type: "NodePort"