#!/bin/bash

cd /var/birthday_organizer
python3 /var/birthday_organizer/manage.py migrate
python3 /var/birthday_organizer/manage.py collectstatic --noinput --clear
if [ "$1" == "include-celery" ]; then
    redis-server --daemonize yes
    celery -A birthday_organizer worker -l DEBUG --logfile=celery_worker.log --detach
    celery -A birthday_organizer beat -l DEBUG --logfile=celery_beat.log --detach
fi
apache2ctl -D FOREGROUND
