# Generated by Django 4.2 on 2023-04-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
