# Generated by Django 4.2 on 2023-05-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_allow_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('STR', 'Strypes'), ('MMM', 'Mint Milk'), ('PRH', 'Purple haze'), ('CPR', 'Caprese'), ('NTV', 'Night vision')], default='STR', max_length=3),
        ),
    ]
