apiVersion: apps/v1
kind: Deployment
metadata:
  name: birthday-organizer-django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: birthday-organizer-django
  template:
    metadata:
      labels:
        app: birthday-organizer-django
    spec:
      containers:
      - name: django
        image: "europe-central2-docker.pkg.dev/birthday-organizer-370909/birthday-organizer-containers/birthday-organizer-django-image:latest"
        ports:
        - containerPort: 80
        env:
        - name: BIRTHDAY_ORGANIZER_ENV
          value: "prd"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgre-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgre-credentials
              key: password
        - name: DJANGO_KEY
          valueFrom:
            secretKeyRef:
              name: django-key
              key: djangokey
