# Generated by Django 4.0.1 on 2023-10-27 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='circles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
